apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: bunker-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: pyx.land/v1alpha1
    resource: bunkers
  childResources:
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: Recreate
  # - apiVersion: v1
  #   resource: services
  #   updateStrategy:
  #     method: Recreate
  # - apiVersion: extensions/v1beta1
  #   resource: ingresses
  #   updateStrategy:
  #     method: Recreate
  hooks:
    sync:
      webhook:
        url: http://bunker-controller.bunker/sync
