apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bunkers.pyx.land
spec:
  group: pyx.land
  version: v1alpha1
  names:
    kind: Bunker
    plural: bunkers
    singular: bunker
  scope: Namespaced
